title: "Gabriel Bizet"
email: "gabriel.bizet.etu@univ-lille.fr"
description: "Portfolio académique – Recherche, clinique, enseignement"

theme: jekyll-theme-cayman

markdown: kramdown

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page

nav:
  - title: "Accueil"
    url: "/"
  - title: "À propos"
    url: "/about/"
  - title: "Pratique Clinique"
    url: "/clinique/"
  - title: "Recherche"
    url: "/recherche/"
  - title: "Enseignement"
    url: "/enseignement/"
  - title: "Activités connexes"
    url: "/autres-activites/"

sass:
  style: compressed

include:
  - assets
